sudo: required
services:
  - docker

before_install:
  - docker build -t peter/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true peter/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-275165835456"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
